config/routes.rb
Microlearning::Application.routes.draw do
  resources :subscribes

  resources :products

  resources :instantiated_products

  resources :students
  
  match '/fetchall', :to => 'products#fetch_all'
  
  

end

app/models/instantiated_product.rb
class InstantiatedProduct < ActiveRecord::Base
  belongs_to :student
  belongs_to :atomicproduct


end

app/controllers/instantiated_products_controller.rb
class InstantiatedProductsController < ApplicationController
  # GET /instantiated_products
  # GET /instantiated_products.xml
  def index
    @instantiated_products = InstantiatedProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @instantiated_products }
    end
  end

  # GET /instantiated_products/1
  # GET /instantiated_products/1.xml
  def show
    @instantiated_product = InstantiatedProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @instantiated_product }
    end
  end

  # GET /instantiated_products/new
  # GET /instantiated_products/new.xml
  def new
    @instantiated_product = InstantiatedProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @instantiated_product }
    end
  end

  # GET /instantiated_products/1/edit
  def edit
    @instantiated_product = InstantiatedProduct.find(params[:id])
  end

  # POST /instantiated_products
  # POST /instantiated_products.xml
  def create
    @instantiated_product = InstantiatedProduct.new(params[:instantiated_product])

    respond_to do |format|
      if @instantiated_product.save
        format.html { redirect_to(@instantiated_product, :notice => 'Instantiated product was successfully created.') }
        format.xml  { render :xml => @instantiated_product, :status => :created, :location => @instantiated_product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @instantiated_product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /instantiated_products/1
  # PUT /instantiated_products/1.xml
  def update
    @instantiated_product = InstantiatedProduct.find(params[:id])

    respond_to do |format|
      if @instantiated_product.update_attributes(params[:instantiated_product])
        format.html { redirect_to(@instantiated_product, :notice => 'Instantiated product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @instantiated_product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /instantiated_products/1
  # DELETE /instantiated_products/1.xml
  def destroy
    @instantiated_product = InstantiatedProduct.find(params[:id])
    @instantiated_product.destroy

    respond_to do |format|
      format.html { redirect_to(instantiated_products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/instantiated_products_helper.rb
module InstantiatedProductsHelper
end

app/views/instantiated_products/_form.html.erb
<%= form_for(@instantiated_product) do |f| %>
  <% if @instantiated_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instantiated_product.errors.count, "error") %> prohibited this instantiated_product from being saved:</h2>

      <ul>
      <% @instantiated_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :begin_date %><br />
    <%= f.date_select :begin_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :atomic_product_id %><br />
    <%= f.text_field :atomic_product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instantiated_products/edit.html.erb
<h1>Editing instantiated_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @instantiated_product %> |
<%= link_to 'Back', instantiated_products_path %>

app/views/instantiated_products/index.html.erb
<h1>Listing instantiated_products</h1>

<table>
  <tr>
    <th>Begin date</th>
    <th>End date</th>
    <th>Status</th>
    <th>Student</th>
    <th>Atomic product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instantiated_products.each do |instantiated_product| %>
  <tr>
    <td><%= instantiated_product.begin_date %></td>
    <td><%= instantiated_product.end_date %></td>
    <td><%= instantiated_product.status %></td>
    <td><%= instantiated_product.student_id %></td>
    <td><%= instantiated_product.atomic_product_id %></td>
    <td><%= link_to 'Show', instantiated_product %></td>
    <td><%= link_to 'Edit', edit_instantiated_product_path(instantiated_product) %></td>
    <td><%= link_to 'Destroy', instantiated_product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instantiated product', new_instantiated_product_path %>

app/views/instantiated_products/new.html.erb
<h1>New instantiated_product</h1>

<%= render 'form' %>

<%= link_to 'Back', instantiated_products_path %>

app/views/instantiated_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Begin date:</b>
  <%= @instantiated_product.begin_date %>
</p>

<p>
  <b>End date:</b>
  <%= @instantiated_product.end_date %>
</p>

<p>
  <b>Status:</b>
  <%= @instantiated_product.status %>
</p>

<p>
  <b>Student:</b>
  <%= @instantiated_product.student_id %>
</p>

<p>
  <b>Atomic product:</b>
  <%= @instantiated_product.atomic_product_id %>
</p>


<%= link_to 'Edit', edit_instantiated_product_path(@instantiated_product) %> |
<%= link_to 'Back', instantiated_products_path %>