config/routes.rb
Microlearning::Application.routes.draw do
  resources :subscribes

  resources :products

  resources :instantiated_products

  resources :students
  
  match '/fetchall', :to => 'products#fetch_all'
  
  

end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  belongs_to :student
  belongs_to :product
  
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  # GET /subscribes
  # GET /subscribes.xml
  def index
    @subscribes = Subscribe.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subscribes }
    end
  end

  # GET /subscribes/1
  # GET /subscribes/1.xml
  def show
    @subscribe = Subscribe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subscribe }
    end
  end

  # GET /subscribes/new
  # GET /subscribes/new.xml
  def new
    @subscribe = Subscribe.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subscribe }
    end
  end

  # GET /subscribes/1/edit
  def edit
    @subscribe = Subscribe.find(params[:id])
  end

  # POST /subscribes
  # POST /subscribes.xml
  def create
    @subscribe = Subscribe.new(params[:subscribe])

    respond_to do |format|
      if @subscribe.save
        format.html { redirect_to(@subscribe, :notice => 'Subscribe was successfully created.') }
        format.xml  { render :xml => @subscribe, :status => :created, :location => @subscribe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subscribe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subscribes/1
  # PUT /subscribes/1.xml
  def update
    @subscribe = Subscribe.find(params[:id])

    respond_to do |format|
      if @subscribe.update_attributes(params[:subscribe])
        format.html { redirect_to(@subscribe, :notice => 'Subscribe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subscribe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribes/1
  # DELETE /subscribes/1.xml
  def destroy
    @subscribe = Subscribe.find(params[:id])
    @subscribe.destroy

    respond_to do |format|
      format.html { redirect_to(subscribes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/_form.html.erb
<%= form_for(@subscribe) do |f| %>
  <% if @subscribe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscribe.errors.count, "error") %> prohibited this subscribe from being saved:</h2>

      <ul>
      <% @subscribe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribes/edit.html.erb
<h1>Editing subscribe</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscribe %> |
<%= link_to 'Back', subscribes_path %>

app/views/subscribes/index.html.erb
<h1>Listing subscribes</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribes.each do |subscribe| %>
  <tr>
    <td><%= subscribe.student_id %></td>
    <td><%= subscribe.product_id %></td>
    <td><%= link_to 'Show', subscribe %></td>
    <td><%= link_to 'Edit', edit_subscribe_path(subscribe) %></td>
    <td><%= link_to 'Destroy', subscribe, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscribe', new_subscribe_path %>

app/views/subscribes/new.html.erb
<h1>New subscribe</h1>

<%= render 'form' %>

<%= link_to 'Back', subscribes_path %>

app/views/subscribes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @subscribe.student_id %>
</p>

<p>
  <b>Product:</b>
  <%= @subscribe.product_id %>
</p>


<%= link_to 'Edit', edit_subscribe_path(@subscribe) %> |
<%= link_to 'Back', subscribes_path %>