config/routes.rb
Microlearning::Application.routes.draw do
  resources :subscribes

  resources :products

  resources :instantiated_products

  resources :students
  
  match '/fetchall', :to => 'products#fetch_all'
  
  

end

app/models/product.rb
require 'net/http'
require 'nokogiri'

class Product < ActiveRecord::Base
  has_many :subscribes
  has_many :students, :through => :subscribes
  
end


class AtomicProduct < Product
  has_many :instantiated_products
  has_many :students, :through => :instantiated_products
  
  validates_presence_of :lms_id, :lms_name, :lms_url 
  validates_uniqueness_of :lms_id, :lms_name, :lms_url
  
  def self.fetch_all
  	connect_to_docebo
  	fetch
  end
    
  private
   
	def self.connect_to_docebo
		@lms = Net::HTTP.new("ec2-46-137-4-94.eu-west-1.compute.amazonaws.com")
	end

  def self.fetch
		request = Net::HTTP::Get.new("/api/rest.php?q=/restAPI/course/courses&auth=yes")
		response = @lms.request(request)
		myDoc = Nokogiri::XML(response.body)
		data = Array.new
		myDoc.root.xpath("//element/course_info").each do |node|
    	data.push({
      	:lms_id => node.xpath("./course_id").text,
	      :lms_name => node.xpath("./course_name").text,
	      :lms_url => node.xpath("./course_link").text
      })
		end
  	data
  end
  
  #def get_token
  	#http = Net::HTTP.new("ec2-46-137-4-94.eu-west-1.compute.amazonaws.com")
  	#request = Net::HTTP::Post.new("/restAPI/auth/authenticate")
	#request.set_form_data({"username" => "admin", "password" => "admin"})
	#response = http.request(request)
  #end
  
end


class CompositeProduct < Product
  serialize :product_ids, Array

  validates_presence_of :product_ids
  
  
  def compositeproducts
    @products ||= Product.find(products_ids)
  end
  
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :instantiated_courses
  has_many :subscribes
  has_many :products, :through => :instantiated_courses
  has_many :products, :through => :subscribes 
  
end

app/controllers/products_controller.rb
require 'product'

class ProductsController < ApplicationController	
  # Get all courses from LMS
  def fetch_all
  	response = AtomicProduct.fetch_all
		
		response.each do |course|
			AtomicProduct.create(course)
		end
  	
  	redirect_to products_path
  end
  
  # GET /products
  # GET /products.xml
  def index
    @products = Product.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :lms_id %><br />
    <%= f.text_field :lms_id %>
  </div>
  <div class="field">
    <%= f.label :lms_name %><br />
    <%= f.text_field :lms_name %>
  </div>
  <div class="field">
    <%= f.label :lms_url %><br />
    <%= f.text_field :lms_url %>
  </div>
  <div class="field">
    <%= f.label :product_ids %><br />
    <%= f.text_field :product_ids %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Type</th>
    <th>Lms</th>
    <th>Lms name</th>
    <th>Lms url</th>
    <th>Product ids</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.label %></td>
    <td><%= product.type %></td>
    <td><%= product.lms_id %></td>
    <td><%= product.lms_name %></td>
    <td><%= product.lms_url %></td>
    <td><%= product.product_ids %></td>
    <td><%= link_to 'Show', product_path(product) %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product_path(product), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Fetch course', fetchall_path %> |
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @product.label %>
</p>

<p>
  <b>Type:</b>
  <%= @product.type %>
</p>

<p>
  <b>Lms:</b>
  <%= @product.lms_id %>
</p>

<p>
  <b>Lms name:</b>
  <%= @product.lms_name %>
</p>

<p>
  <b>Lms url:</b>
  <%= @product.lms_url %>
</p>

<p>
  <b>Product ids:</b>
  <%= @product.product_ids %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>